name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Rustup
        run: rustup default stable
      - uses: Swatinem/rust-cache@v2
      - name: Prepare
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y libxkbcommon-dev
          cp ./client/config/server.template.json ./client/config/server.json
      - name: Format
        run: cargo fmt --all -- --check
      - name: Compile
        run: cargo test --no-run --locked
      - name: Tests
        run: cargo test --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
