name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Prepare
        run: |
          sudo apt-get install -y libxkbcommon-dev
          cp ./api/config/aws.template.json ./api/config/aws.json
          cp ./client/config/server.template.json ./client/config/server.json
      - name: Format
        run: cargo fmt --all -- --check
      - name: Compile
        run: cargo test --no-run --locked
      - name: Tests
        run: cargo test --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
